//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.WinForms.Message {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Registrstion.WinForms.Message.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 165.
        /// </summary>
        internal static string ColumnWidth {
            get {
                return ResourceManager.GetString("ColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? | Delete folder.
        /// </summary>
        internal static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? | Delete letter.
        /// </summary>
        internal static string DeleteLetter {
            get {
                return ResourceManager.GetString("DeleteLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of recipient should not be empty! | Make message error.
        /// </summary>
        internal static string EmptyListRecipient {
            get {
                return ResourceManager.GetString("EmptyListRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login must not be empty! | Registration error.
        /// </summary>
        internal static string EmptyLogin {
            get {
                return ResourceManager.GetString("EmptyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or password is empty! | Authorization error .
        /// </summary>
        internal static string EmptyLoginOrPassword {
            get {
                return ResourceManager.GetString("EmptyLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must not be empty! | Registration error.
        /// </summary>
        internal static string EmptyName {
            get {
                return ResourceManager.GetString("EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must not be empty! | Make message error.
        /// </summary>
        internal static string EmptyNameInLetter {
            get {
                return ResourceManager.GetString("EmptyNameInLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must not be empty! | Registration error .
        /// </summary>
        internal static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such worker is exist! | Sing up error.
        /// </summary>
        internal static string ExistWorker {
            get {
                return ResourceManager.GetString("ExistWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter name.
        /// </summary>
        internal static string LetterName {
            get {
                return ResourceManager.GetString("LetterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The letter for delete is not select! | Delete error.
        /// </summary>
        internal static string LetterNotSelect {
            get {
                return ResourceManager.GetString("LetterNotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change folder.
        /// </summary>
        internal static string MenuChangeFolder {
            get {
                return ResourceManager.GetString("MenuChangeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder.
        /// </summary>
        internal static string MenuCreateFolder {
            get {
                return ResourceManager.GetString("MenuCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder.
        /// </summary>
        internal static string MenuDeleteFolder {
            get {
                return ResourceManager.GetString("MenuDeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such worker not exist! | Make message error.
        /// </summary>
        internal static string NonexistWorker {
            get {
                return ResourceManager.GetString("NonexistWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        internal static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The letter was sent! | Sending letter.
        /// </summary>
        internal static string SentLetter {
            get {
                return ResourceManager.GetString("SentLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration is successfull! | Sing Up.
        /// </summary>
        internal static string SuccessfullRegistration {
            get {
                return ResourceManager.GetString("SuccessfullRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welocome! |.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or password is wrong | Authorization error.
        /// </summary>
        internal static string WrongLoginOrPassword {
            get {
                return ResourceManager.GetString("WrongLoginOrPassword", resourceCulture);
            }
        }
    }
}
